// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab2;

#nullable disable

namespace lab2.Migrations
{
    [DbContext(typeof(kantor))]
    [Migration("20240327151243_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("lab2.info_walut", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalutaDb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WartoscDb")
                        .HasColumnType("REAL");

                    b.HasKey("Index");

                    b.ToTable("Baza_Danych");
                });
#pragma warning restore 612, 618
        }
    }
}
